routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    if(session('login')) {
        if(session('user')->role === 'admin') {
            return redirect(route('admin.post.index'));
        } else {
            return redirect(route('post.index'));
        }
    } else {
        return redirect(route('siswa.login'));
    }
});

Route::get('/author', function () {
    return view('author\index');
})->name('author');

Route::get('admin/login', 'AuthController@adminLogin')->name('admin.login');
Route::post('admin/doLogin', 'AuthController@adminDoLogin')->name('admin.doLogin');
Route::get('siswa/login', 'AuthController@siswaLogin')->name('siswa.login');
Route::post('siswa/doLogin', 'AuthController@siswaDoLogin')->name('siswa.doLogin');
Route::get('logout', 'AuthController@logout')->name('logout');

Route::group(['middleware' => ['authLogin', 'isSiswa']], function() {
    Route::resource('post', 'PostController', ['except' => ['create', 'store', 'edit', 'update', 'destroy']]);
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['authLogin', 'isAdmin']], function() {
    Route::name('admin.')->group(function() {
        Route::resource('post', 'PostController');
    });
});

Route::get('post/download/{id}', 'PostController@download')->name('post.download');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $guarded = ['id'];
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User, App\Models\Post, App\Models\Pengajar;
use DataTables;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $posts = Post::query()->where('id_user', User::getUserBySession()->id)->orderBy('created_at', 'DESC');
            return DataTables::of($posts)
                ->addColumn('title', function ($posts) {
                    return \Illuminate\Support\Str::limit($posts->title, 8);
                })
                ->addColumn('tanggal', function ($posts) {
                    return \Carbon\Carbon::parse($posts->created_at)->translatedFormat('l, d F Y');
                })
                ->addColumn('action', function ($posts) {
                    $button = "<a href=" . route('admin.post.show', $posts->id) . " class='btn btn-info btn-sm'><i class='far fa-eye'></i></a>";
                    $button .= "&nbsp;";
                    $button .= "<a href=" . route('admin.post.edit', $posts->id) . " class='btn btn-warning btn-sm'><i class='fas fa-pencil-alt'></i></a>";
                    $button .= "&nbsp;";
                    $button .= "<form method='post' action='" . route('admin.post.destroy', $posts->id) . "' style='display: inline;'>" . method_field('DELETE') . csrf_field() . " <button type='submit' class='btn btn-danger btn-sm'><i class='fas fa-trash-alt'></i></button></form>";

                    return $button;
                })
                ->rawColumns(['title', 'tanggal', 'action'])
                ->make(true);
        }

        return view('pages.admin.posts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $pengajar = Pengajar::getPengajar(session('user')->id);

        return view('pages.admin.posts.create', compact('pengajar'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $ytId = getYoutubeID($request->url);
        // Validasi
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required',
            'kelas' => 'required',
            'mapel' => 'required',
        ]);

        try {
            $file = $request->file('document');
            // Validate Image
            if ($file) {
                $request->validate([
                    'document' => 'max:20000|mimes:jpeg,jpg,png,pdf,ppt,pptx,xlx,xlsx,docx,doc'
                ]);

                $ext = $file->guessExtension();
                $filename = md5(time() . date('dmY H:i:s')) . '.' . $ext;
                $file->storeAs('docs', $filename, 'public');
            }

            Post::create([
                'title' => $request->title,
                'description' => $request->description,
                'document' => is_null($file) ? null : $filename,
                'url' => $ytId === 0 ? NULL : $ytId,
                'id_user' => User::getUserBySession()->id,
                'id_kelas' => $request->kelas,
                'id_mapel' => $request->mapel,
            ]);

            return redirect(route('admin.post.index'))->with('success', 'Materi berhasil di publish');
        } catch (\Exception $exc) {
            return redirect(route('admin.post.create'))->with('error', 'Terjadi kesalahan');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);

        return view('pages.admin.posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $pengajar = Pengajar::getPengajar(session('user')->id);

        return view('pages.admin.posts.edit', compact('post', 'pengajar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $ytId = getYoutubeID($request->url);
        // Validasi
        $request->validate([
            'title' => 'required|max:255',
            'description' => 'required',
            'kelas' => 'required',
            'mapel' => 'required',
        ]);

        try {
            $post = Post::findOrFail($id);

            $file = $request->file('document');
            // Validate Image
            if ($file) {
                $request->validate([
                    'document' => 'max:20000|mimes:jpeg,jpg,png,pdf'
                ]);

                $ext = $file->guessExtension();
                $filename = md5(time() . date('dmY H:i:s')) . '.' . $ext;
                $file->storeAs('docs', $filename, 'public');

                if ($post->document) {
                    unlink(public_path('storage/docs/' . $post->document));
                }
            }
            $post->update([
                'title' => $request->title,
                'description' => $request->description,
                'document' => is_null($file) ? $post->document : $filename,
                'url' => $ytId === 0 ? NULL : $ytId,
                'id_user' => User::getUserBySession()->id,
                'id_kelas' => $request->kelas,
                'id_mapel' => $request->mapel,
            ]);

            return redirect(route('admin.post.index'))->with('success', 'Materi berhasil di perbarui');
        } catch (\Exception $exc) {
            return redirect(route('admin.post.create'))->with('error', 'Terjadi kesalahan');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::findOrFail($id);
        $post->delete();

        return redirect(route('admin.post.index'))->with('success', 'Materi berhasil di hapus');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User, App\Models\Post, App\Models\Siswa, App\Models\Mapel;
use Illuminate\Support\Facades\Storage;
use DataTables;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $posts = Post::query()->where('id_kelas', Siswa::getBySession()->kelas->kelas_id)->orderBy('created_at', 'DESC');
            
            return DataTables::of($posts)
                            ->addColumn('post', function($posts) {
                                return \Illuminate\Support\Str::limit($posts->post, 8);
                            })
                            ->addColumn('tanggal', function($posts) {
                                return \Carbon\Carbon::parse($posts->created_at)->translatedFormat('l, d F Y');
                            })
                            ->addColumn('action', function($jurnal) {
                                $button = "<a href=" . route('post.show', $jurnal->id) . " class='btn btn-info btn-sm'><i class='far fa-eye'></i></a>";
                                return $button;
                            })
                            ->rawColumns(['post', 'tanggal', 'action'])
                            ->make(true);
        }

        return view('pages.posts.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $kelas_id = Siswa::getBySession()->kelas->kelas_id;
        $post = Post::findOrFail($id);

        if($post->id_kelas != $kelas_id) {
            return redirect(route('post.index'))->with('error', 'Terjadi kesalahan');
        }
        return view('pages.admin.posts.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * Download Post File
    */

    public function download($id) {
        $post = Post::findOrFail($id);

        return Storage::disk('local')->download('public/docs/'.$post->document);
    }
}

resources/views/pages/admin/posts/create.blade.php
@extends('layouts.app')

@section('title', 'Buat Post')

@section('content')
    <!-- Main Content -->
        <div class="main-content">
            <section class="section">
            <div class="section-header">
                <h1>@yield('title')</h1>
                <a href="{{ route('admin.post.index') }}" class="btn btn-warning ml-auto"><i class="fas fa-arrow-left"></i> Kembali</a>
            </div>
            @include('components.message')
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <form action="{{ route('admin.post.store') }}" method="post" enctype="multipart/form-data">
                            <div class="card">
                                <div class="card-body">
                                    @csrf
                                    <div class="form-group">
                                        <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Title" value="{{ old('title') }}" autocomplete="off" autofocus>
                                        @error('title')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <textarea class="form-control @error('description') is-invalid @enderror" name="description" placeholder="Description">{{ old('description') }}</textarea>
                                        @error('description')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input @error('document') is-invalid @enderror" name="document" placeholder="document" id="document">
                                            <label class="custom-file-label" for="document">Choose file</label>
                                        </div>
                                        @error('document')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control @error('url') is-invalid @enderror" name="url" placeholder="Youtube URL (Opsional)" value="{{ old('url') }}" autocomplete="off" autofocus>
                                        @error('url')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <div class="form-group">
                                        <select name="kelas" id="kelas" class="form-control @error('kelas') is-invalid @enderror">
                                            <option value=""> Pilih kelas</option>
                                            @foreach($pengajar as $pengajarKelas)
                                                <option value="{{ $pengajarKelas->kelas->id }}" @if(old('kelas') == $pengajarKelas->kelas->id) selected @endif> {{ $pengajarKelas->kelas->nama_kelas }}</option>
                                            @endforeach
                                        </select>
                                        @error('kelas')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <select name="mapel" id="mapel" class="form-control @error('mapel') is-invalid @enderror">
                                            <option value=""> Pilih mapel</option>
                                            @foreach($pengajar as $pengajarMapel)
                                                <option value="{{ $pengajarMapel->mapel->id }}" @if(old('mapel') == $pengajarMapel->mapel->id) selected @endif> {{ $pengajarMapel->mapel->nama_mapel}} | Kelas : {{ $pengajarMapel->mapel->tingkat  }}</option>
                                            @endforeach
                                        </select>
                                        @error('mapel')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <button class="btn btn-primary float-right"><i class="fas fa-save"></i> Simpan</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            </section>
        </div>
@endsection

resources/views/pages/admin/posts/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Post')

@section('content')
    <!-- Main Content -->
        <div class="main-content">
            <section class="section">
            <div class="section-header">
                <h1>@yield('title')</h1>
                <a href="{{ route('admin.post.index') }}" class="btn btn-warning ml-auto"><i class="fas fa-arrow-left"></i> Kembali</a>
            </div>
            @include('components.message')
            <div class="section-body">
                <div class="row">
                    <div class="col-lg-8 col-md-8">
                        <form action="{{ route('admin.post.update', $post->id) }}" method="post" enctype="multipart/form-data">
                            <div class="card">
                                <div class="card-body">
                                    @method('put')
                                    @csrf
                                    <div class="form-group">
                                        <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" placeholder="Title" value="{{ $post->title }}" autocomplete="off" autofocus>
                                        @error('title')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <textarea class="form-control @error('description') is-invalid @enderror" name="description" placeholder="Description">{{ $post->description }}</textarea>
                                        @error('description')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-file">
                                            <input type="file" class="custom-file-input @error('document') is-invalid @enderror" name="document" placeholder="document" id="document" accept="image/png, image/jpeg, application/pdf">
                                            <label class="custom-file-label" for="document">Choose file</label>
                                        </div>
                                        @error('document')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <input type="text" class="form-control @error('url') is-invalid @enderror" name="url" placeholder="Youtube URL (Opsional)" value="https://www.youtube.com/watch?v={{ $post->url }}" autocomplete="off" autofocus>
                                        @error('url')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-4">
                            <div class="card">
                                <div class="card-body">
                                    <div class="form-group">
                                        <select name="kelas" id="kelas" class="form-control @error('kelas') is-invalid @enderror">
                                            <option value=""> Pilih kelas</option>
                                            @foreach($pengajar as $pengajarKelas)
                                                <option value="{{ $pengajarKelas->kelas->id }}" @if($post->id_kelas == $pengajarKelas->kelas->id) selected @endif> {{ $pengajarKelas->kelas->nama_kelas }}</option>
                                            @endforeach
                                        </select>
                                        @error('kelas')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <div class="form-group">
                                        <select name="mapel" id="mapel" class="form-control @error('mapel') is-invalid @enderror">
                                            <option value=""> Pilih mapel</option>
                                            @foreach($pengajar as $pengajarMapel)
                                                <option value="{{ $pengajarMapel->mapel->id }}" @if($post->id_mapel == $pengajarMapel->mapel->id) selected @endif> {{ $pengajarMapel->mapel->nama_mapel}} | Kelas : {{ $pengajarMapel->mapel->tingkat  }}</option>
                                            @endforeach
                                        </select>
                                        @error('mapel')
                                            <div class="invalid-feedback">
                                                <strong>{{ $message }}</strong>
                                            </div>
                                        @enderror
                                    </div>
                                    <button class="btn btn-primary float-right"><i class="fas fa-save"></i> Simpan</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            </section>
        </div>
@endsection

resources/views/pages/admin/posts/index.blade.php
@extends('layouts.app')

@section('title', 'Post')

@section('content')
    <!-- Main Content -->
        <div class="main-content">
            <section class="section">
            <div class="section-header">
                <h1>@yield('title')</h1>
                <a href="{{ route('admin.post.create') }}" class="btn btn-primary ml-auto"><i class="fas fa-plus"></i> Baru</a>
            </div>
            @include('components.message')
            <div class="section-body">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped" id="table">
                                <thead>
                                    <tr>
                                        <th>#ID</th>
                                        <th>Judul</th>
                                        <th>Tanggal</th>
                                        <th>Lainnya</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            </section>
        </div>
@endsection

@section('script')
<script type="text/javascript">
    $(document).ready(function() {
        $('#table').DataTable({
            processing: true,
            serverSide: true,
            stateSave: true,
            ajax: {
                url: "{{ route('admin.post.index') }}"
            },
            responsive: true,
            "columns": [
                {
                    data: 'id',
                    name: 'id',
                    orderable: false
                },
                {
                    data: 'title',
                    name: 'title',
                    orderable: false
                },
                {
                    data: 'tanggal',
                    name: 'tanggal',
                    orderable: false
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false
                }
            ]
        })
    });
</script>
@endsection

resources/views/pages/admin/posts/show.blade.php
@extends('layouts.app')

@section('title', 'Post')

@section('content')
    <!-- Main Content -->
        <div class="main-content">
            <section class="section">
                <div class="section-header">
                    <h1>@yield('title')</h1>
                    <a href="{{ route('admin.post.index') }}" class="btn btn-warning ml-auto"><i class="fas fa-arrow-left"></i> Kembali</a>
                </div>
                @include('components.message')
                <div class="section-body">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="card">
                                <div class="card-header post-header">
                                    <h4>{{ $post->title }}</h4>
                                </div>
                                <div class="card-body post-body">
                                    <p>{{ $post->description }}</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card">
                                        <div class="card-body">
                                            @if($post->url)
                                            <iframe class="video" src="https://www.youtube.com/embed/{{ $post->url }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                            @else
                                            Tidak ada video
                                            @endif
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-12">
                                    <div class="card">
                                        <div class="card-body">
                                            @if($post->document != null)
                                                <a href="{{ route('post.download', $post->id) }}" class="btn btn-primary btn-block"><i class="fas fa-download"></i> Download File</a>
                                            @else
                                            Tidak ada dokumen
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
@endsection